# Generated by Django 6.0.6 on 2026-06-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('besoin_eau', models.FloatField()),
                ('besoin_engrais', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField(help_text='Superficie en hectares')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferme.culture')),
            ],
        ),
    ]
