# Generated by Django 6.0.6 on 2026-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='besoin_engrais',
        ),
        migrations.AddField(
            model_name='culture',
            name='azote',
            field=models.FloatField(default=0, help_text='Azote (kg/ha)'),
        ),
        migrations.AddField(
            model_name='culture',
            name='phosphore',
            field=models.FloatField(default=0, help_text='Phosphore (kg/ha)'),
        ),
        migrations.AddField(
            model_name='culture',
            name='potassium',
            field=models.FloatField(default=0, help_text='Potassium (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='besoin_eau',
            field=models.FloatField(default=0, help_text='Besoins en eau (mm/semaine)'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='superficie',
            field=models.FloatField(),
        ),
    ]
