# Generated by Django 6.0.6 on 2026-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0002_remove_culture_besoin_engrais_culture_azote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='latitude',
            field=models.FloatField(default=14.6937),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='longitude',
            field=models.FloatField(default=-17.4441),
        ),
        migrations.AlterField(
            model_name='culture',
            name='azote',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='culture',
            name='besoin_eau',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='culture',
            name='phosphore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='culture',
            name='potassium',
            field=models.FloatField(default=0),
        ),
    ]
