# Generated by Django 6.0.6 on 2026-06-27 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0003_parcelle_latitude_parcelle_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_capteur', models.CharField(choices=[('temperature', 'Température'), ('humidite', 'Humidité'), ('luminosite', 'Luminosité')], max_length=20)),
                ('valeur', models.FloatField()),
                ('date_mesure', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferme.parcelle')),
            ],
        ),
    ]
